version = 1

[[annotations]]
path = [
".vscode/settings.json",
".python-version",
".devcontainer/devcontainer.json"
]
SPDX-FileCopyrightText = "2025 Aaron White <w531t4@gmail.com>"
SPDX-License-Identifier = "MIT"
